import { AppTheme } from './types';

// Eight slide templates, each a visually DISTINCT design — different layout,
// chrome and personality — not just a recolor of the same slide.
export const THEMES: AppTheme[] = [
  {
    // Matches the projected Project Lesson deck, so a slide edited here looks
    // like the lesson the class will actually see.
    id: 'tpl-deck',
    name: 'Teaching Deck',
    designType: 'deck',
    bgColor: '#0A4F29',
    cardBg: '#FFFFFF',
    textColor: '#12140F',
    accentColor: '#0A4F29',
    secondaryColor: '#F7B917',
    titleColor: '#12140F',
    patternType: 'dots',
    emoji: '🌟',
  },
  {
    id: 'tpl-band',
    name: 'Color Band',
    designType: 'band',
    bgColor: '#F8FAF5',
    cardBg: '#FFFFFF',
    textColor: '#1A2E22',
    accentColor: '#0A4F29',
    secondaryColor: '#F7B917',
    titleColor: '#FFFFFF',
    patternType: 'school',
    emoji: '🎨',
  },
  {
    id: 'tpl-doodle',
    name: 'Doodle Sketch',
    designType: 'doodle',
    bgColor: '#FFFFFF',
    cardBg: '#FFFFFF',
    textColor: '#111111',
    accentColor: '#111111',
    secondaryColor: '#111111',
    patternType: 'dots',
    emoji: '✏️',
  },
  {
    id: 'tpl-paper',
    name: 'Paper & Tape',
    designType: 'paper',
    bgColor: '#BAE6FD',
    cardBg: '#FFFFFF',
    textColor: '#0C4A6E',
    accentColor: '#0369A1',
    secondaryColor: '#F59E0B',
    patternType: 'waves',
    emoji: '📌',
  },
  {
    id: 'tpl-blob',
    name: 'Playful Blobs',
    designType: 'blob',
    bgColor: '#FDF2F8',
    cardBg: '#FFFFFF',
    textColor: '#831843',
    accentColor: '#EC4899',
    secondaryColor: '#8B5CF6',
    patternType: 'stars',
    emoji: '🎈',
  },
  {
    id: 'tpl-gradient',
    name: 'Gradient Glow',
    designType: 'gradient',
    bgColor: '#7C3AED',
    cardBg: '#FFFFFF',
    textColor: '#FFFFFF',
    accentColor: '#FDE047',
    secondaryColor: '#EC4899',
    titleColor: '#FFFFFF',
    patternType: 'stars',
    emoji: '🌈',
  },
  {
    id: 'tpl-clouds',
    name: 'Sunny Sky',
    designType: 'clouds',
    bgColor: '#E0F2FE',
    cardBg: '#FFFFFF',
    textColor: '#075985',
    accentColor: '#0EA5E9',
    secondaryColor: '#FBBF24',
    patternType: 'clouds',
    emoji: '⛅',
  },
  {
    id: 'tpl-chalk',
    name: 'Chalkboard',
    designType: 'chalk',
    bgColor: '#0B3D2E',
    cardBg: '#11503C',
    textColor: '#ECFDF5',
    accentColor: '#FDE68A',
    secondaryColor: '#86EFAC',
    titleColor: '#FFFFFF',
    patternType: 'school',
    emoji: '🧑‍🏫',
  },
  {
    id: 'tpl-minimal',
    name: 'Minimal Pro',
    designType: 'minimal',
    bgColor: '#FFFFFF',
    cardBg: '#FFFFFF',
    textColor: '#1E293B',
    accentColor: '#0F172A',
    secondaryColor: '#64748B',
    patternType: 'dots',
    emoji: '◽',
  },
  {
    id: 'tpl-notebook',
    name: 'Notebook',
    designType: 'notebook',
    bgColor: '#FFFFFF',
    cardBg: '#FFFFFF',
    textColor: '#1F2937',
    accentColor: '#E25555',
    secondaryColor: '#93B8DC',
    patternType: 'school',
    emoji: '📓',
  },
  {
    id: 'tpl-neon',
    name: 'Neon Night',
    designType: 'neon',
    bgColor: '#0B1026',
    cardBg: '#141A35',
    textColor: '#E2E8F0',
    accentColor: '#22D3EE',
    secondaryColor: '#F472B6',
    titleColor: '#FFFFFF',
    patternType: 'dots',
    emoji: '🌌',
  },
  {
    id: 'tpl-sticky',
    name: 'Sticky Notes',
    designType: 'sticky',
    bgColor: '#F7EBD8',
    cardBg: '#FFFFFF',
    textColor: '#4A3520',
    accentColor: '#B45309',
    secondaryColor: '#FCD34D',
    patternType: 'dots',
    emoji: '📝',
  },
  {
    id: 'tpl-memphis',
    name: 'Memphis Pop',
    designType: 'memphis',
    bgColor: '#FFFBF0',
    cardBg: '#FFFFFF',
    textColor: '#27272A',
    accentColor: '#F43F5E',
    secondaryColor: '#14B8A6',
    patternType: 'stars',
    emoji: '🎉',
  },
  {
    id: 'tpl-botanical',
    name: 'Botanical',
    designType: 'botanical',
    bgColor: '#F6F8F2',
    cardBg: '#FFFFFF',
    textColor: '#2D3B2E',
    accentColor: '#4A6B4F',
    secondaryColor: '#C9A227',
    patternType: 'school',
    emoji: '🌿',
  },
  {
    id: 'tpl-origami',
    name: 'Origami',
    designType: 'origami',
    bgColor: '#F4F7FB',
    cardBg: '#FFFFFF',
    textColor: '#1E3A5F',
    accentColor: '#2563EB',
    secondaryColor: '#93C5FD',
    patternType: 'waves',
    emoji: '📐',
  },
  {
    id: 'tpl-bubbles',
    name: 'Bubbles',
    designType: 'bubbles',
    bgColor: '#E3F6F8',
    cardBg: '#FFFFFF',
    textColor: '#0C4A57',
    accentColor: '#0E7490',
    secondaryColor: '#67E8F9',
    patternType: 'waves',
    emoji: '🫧',
  },
  {
    id: 'tpl-candy',
    name: 'Candy Shop',
    designType: 'candy',
    bgColor: '#FFF4F7',
    cardBg: '#FFFFFF',
    textColor: '#7A2547',
    accentColor: '#EC4899',
    secondaryColor: '#A78BFA',
    patternType: 'stars',
    emoji: '🍭',
  },
];

// Kept for backwards compatibility — the generated recolor variants were
// removed because they all looked identical apart from the palette.
export const GENERATED_THEMES: AppTheme[] = [];
