import { AppTheme } from './types';

// Eight slide templates, each a visually DISTINCT design — different layout,
// chrome and personality — not just a recolor of the same slide.
export const THEMES: AppTheme[] = [
  {
    id: 'tpl-band',
    name: 'Color Band',
    designType: 'band',
    bgColor: '#F8FAF5',
    cardBg: '#FFFFFF',
    textColor: '#1A2E22',
    accentColor: '#0A4F29',
    secondaryColor: '#F7B917',
    titleColor: '#FFFFFF',
    patternType: 'school',
    emoji: '🎨',
  },
  {
    id: 'tpl-doodle',
    name: 'Doodle Sketch',
    designType: 'doodle',
    bgColor: '#FFFFFF',
    cardBg: '#FFFFFF',
    textColor: '#111111',
    accentColor: '#111111',
    secondaryColor: '#111111',
    patternType: 'dots',
    emoji: '✏️',
  },
  {
    id: 'tpl-paper',
    name: 'Paper & Tape',
    designType: 'paper',
    bgColor: '#BAE6FD',
    cardBg: '#FFFFFF',
    textColor: '#0C4A6E',
    accentColor: '#0369A1',
    secondaryColor: '#F59E0B',
    patternType: 'waves',
    emoji: '📌',
  },
  {
    id: 'tpl-blob',
    name: 'Playful Blobs',
    designType: 'blob',
    bgColor: '#FDF2F8',
    cardBg: '#FFFFFF',
    textColor: '#831843',
    accentColor: '#EC4899',
    secondaryColor: '#8B5CF6',
    patternType: 'stars',
    emoji: '🎈',
  },
  {
    id: 'tpl-gradient',
    name: 'Gradient Glow',
    designType: 'gradient',
    bgColor: '#7C3AED',
    cardBg: '#FFFFFF',
    textColor: '#FFFFFF',
    accentColor: '#FDE047',
    secondaryColor: '#EC4899',
    titleColor: '#FFFFFF',
    patternType: 'stars',
    emoji: '🌈',
  },
  {
    id: 'tpl-clouds',
    name: 'Sunny Sky',
    designType: 'clouds',
    bgColor: '#E0F2FE',
    cardBg: '#FFFFFF',
    textColor: '#075985',
    accentColor: '#0EA5E9',
    secondaryColor: '#FBBF24',
    patternType: 'clouds',
    emoji: '⛅',
  },
  {
    id: 'tpl-chalk',
    name: 'Chalkboard',
    designType: 'chalk',
    bgColor: '#0B3D2E',
    cardBg: '#11503C',
    textColor: '#ECFDF5',
    accentColor: '#FDE68A',
    secondaryColor: '#86EFAC',
    titleColor: '#FFFFFF',
    patternType: 'school',
    emoji: '🧑‍🏫',
  },
  {
    id: 'tpl-minimal',
    name: 'Minimal Pro',
    designType: 'minimal',
    bgColor: '#FFFFFF',
    cardBg: '#FFFFFF',
    textColor: '#1E293B',
    accentColor: '#0F172A',
    secondaryColor: '#64748B',
    patternType: 'dots',
    emoji: '◽',
  },
];

// Kept for backwards compatibility — the generated recolor variants were
// removed because they all looked identical apart from the palette.
export const GENERATED_THEMES: AppTheme[] = [];
